sudo: required
services:
  - docker

before_install:
  - docker build -t alisher83/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true alisher83/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-050698091163"
  bucket_path: "docker"
  on: 
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
