sudo: required
services:
  - docker

before_install:
  - docker build -t alisher83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alisher83/react-test npm run test

after_success:
  - docker build -t alisher83/multi-client ./client
  - docker build -t alisher83/multi-nginx ./nginx
  - docker build -t alisher83/multi-server ./server
  - docker build -t alisher83/multi-worker ./worker
  # loging to docker cli and push containers
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push alisher83/multi-client
  - docker push alisher83/multi-nginx
  - docker push alisher83/multi-server
  - docker push alisher83/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-050698091163"
  bucket_path: "docker-multi"
  on: 
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY